import { relations } from "drizzle-orm";
import {
  boolean,
  char,
  datetime,
  float,
  index,
  int,
  mysqlEnum,
  mysqlTable,
  primaryKey,
  smallint,
  text,
  varchar,
} from "drizzle-orm/mysql-core";

export const airmets = mysqlTable(
  "airmets",
  {
    issueTime: datetime().notNull(),
    endTime: datetime().notNull(),
    charCode: varchar({ length: 20 }).default("-").notNull(),
    numberCode: smallint().default(0).notNull(),
    initialShape: mysqlEnum(["polygon", "line", "point"]),
    initialBufferSize: int(),
    speed: int(),
    initialCoords: text(),
    initialCentre: text(),
    rawText: text().notNull(),
    domain: text(),
    issuer: text(),
    firRegion: text(),
    header: varchar({ length: 6 }).default("TEMP").notNull(),
    hazard: text(),
    hazardTrend: mysqlEnum(["NC", "INTSF", "WKN"]),
    hazardBottom: text(),
    hazardTop: text(),
    direction: float(),
  },
  (table) => [
    primaryKey({
      columns: [table.header, table.issueTime, table.charCode, table.numberCode],
      name: "airmets_pk",
    }),
  ],
);

export const pireps = mysqlTable(
  "pireps",
  {
    id: int().autoincrement().notNull(),
    issuingOffice: text(),
    reportType: text(),
    validTime: datetime({ mode: "date" }),
    issueTime: datetime({ mode: "date" }),
    lat: float(),
    lon: float(),
    rawText: text(),
    ws: boolean(),
    sky: text(),
    aircraftType: text(),
    fir: text(),
    flightLevel: int(),
    icing: text(),
    turbulence: text(),
  },
  (table) => [primaryKey({ columns: [table.id], name: "pireps_id" })],
);

export const sigmets = mysqlTable(
  "sigmets",
  {
    issueTime: datetime().notNull(),
    endTime: datetime().notNull(),
    charCode: varchar({ length: 20 }).default("-").notNull(),
    numberCode: smallint().default(0).notNull(),
    initialShape: mysqlEnum(["polygon", "line", "point"]),
    initialBufferSize: int(),
    speed: int(),
    initialCoords: text(),
    finalCoords: text(),
    initialCentre: text(),
    finalCentre: text(),
    rawText: text().notNull(),
    domain: text(),
    issuer: text(),
    firRegion: text(),
    header: varchar({ length: 6 }).default("TEMP").notNull(),
    hazard: text(),
    hazardName: text(),
    hazardTrend: mysqlEnum(["NC", "INTSF", "WKN"]),
    hazardBottom: text(),
    hazardTop: text(),
    finalShape: mysqlEnum(["polygon", "line", "point"]),
    finalBufferSize: int(),
    direction: float(),
  },
  (table) => [
    primaryKey({
      columns: [table.header, table.issueTime, table.charCode, table.numberCode],
      name: "sigmets_pk",
    }),
  ],
);

export const stations = mysqlTable(
  "stations",
  {
    siteId: varchar({ length: 4 }).notNull(),
    climateId: int(),
    country: varchar({ length: 3 }),
    siteName: text().notNull(),
    lon: float().notNull(),
    lat: float().notNull(),
    elev_m: float(),
    elev_f: float(),
    altVis: float(),
    altCig: int(),
    ldgVis: float(),
    ldgCig: int(),
  },
  (table) => [primaryKey({ columns: [table.siteId], name: "stations_siteId" })],
);

export const tafs = mysqlTable(
  "taf",
  {
    id: int().autoincrement().notNull(),
    validTime: datetime("valid_timestamp").notNull(),
    issueTime: datetime("issued_timestamp").notNull(),
    site: varchar("station", { length: 4 }).notNull(),
    raw: text("rawText").notNull(),
    parsed: text("parsedObj").notNull(),
  },
  (table) => [
    index("station").on(table.site),
    index("issued").on(table.issueTime),
    index("valid").on(table.validTime),
    primaryKey({ columns: [table.id], name: "taf_id" }),
  ],
);

export const nswob = mysqlTable(
  "nswob",
  () => ({
    id: int().autoincrement().notNull(),
    stationId: varchar({ length: 50 }).notNull(),
    stationName: varchar({ length: 50 }),
    validTime: datetime().notNull(),
    issueTime: datetime().notNull(),
    stationType: mysqlEnum([
      "MOORED_BUOY",
      "DRIFTING_BUOY",
      "FM_BUOY",
      "SHIP",
      "LAND",
      "LIGHTHOUSE",
      "LAND_MANNED",
      "LAND_AUTO",
      "THIRD_PARTY",
      "SURFACE_ANALYSIS",
      "OTHER",
    ]).notNull(),
    rawDataType: varchar({ length: 50 }),
    dataSource: varchar({ length: 50 }),
    messageType: varchar({ length: 50 }),
    correctionLevel: char({ length: 3 }),
    lat: float().notNull(),
    lon: float().notNull(),
    ceiling: int(),
    visibility: float(),
    relativeHumidity: float(),
    relativeHumidityMin24: float(),
    relativeHumidityMax24: float(),
    windDir: int(),
    windDirAvg10: int(),
    windDirPeak: int(),
    windDirVarMin: int(),
    windDirVarMax: int(),
    windSpd: int(),
    windSpdAvg10: int(),
    windSpdPeak: int(),
    windSpdMax10: int(),
    peakWindTime: datetime(),
    windShear: varchar({ length: 20 }),
    tt: float(),
    td: float(),
    ts: float(),
    ttMax1: float(),
    ttMax6: float(),
    ttMax24: float(),
    ttMin1: float(),
    ttMin6: float(),
    ttMin24: float(),
    mslp: float(),
    stationPressure: float(),
    pressureTendency: float(),
    altimeter: float(),
    precip1hr: int(),
    precip3hr: int(),
    precip6hr: int(),
    precip12hr: int(),
    precip24hr: int(),
    clouds: varchar({ length: 50 }),
    rvr: varchar({ length: 50 }),
    snowOnGroud: float(),
    waveHeight: float(),
    wavePeriod: float(),
    shipDir: float(),
    shipSpd: float(),
    wx: varchar({ length: 50 }),
    rmk: varchar({ length: 100 }),
    rawText: varchar({ length: 150 }),
  }),
  (table) => [
    primaryKey({ columns: [table.validTime, table.stationId, table.lat, table.lon] }),
    index("idx_id").on(table.id),
  ],
);

// one station has many nswobs and one taf
export const stationRelations = relations(stations, ({ many, one }) => ({
  nswob: many(nswob),
  tafs: one(tafs),
}));

// one nswob has one station
export const nswobRelations = relations(nswob, ({ one }) => ({
  stations: one(stations, { fields: [nswob.stationId], references: [stations.siteId] }),
}));

// one taf has one station
export const tafsRelations = relations(tafs, ({ one }) => ({
  stations: one(stations, { fields: [tafs.site], references: [stations.siteId] }),
}));
