services:
  redis:
    image: redis:8
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  db:
    container_name: db
    image: postgis/postgis:17-3.5
    restart: unless-stopped
    volumes:
      - pg_data:/var/lib/postgresql/data
      - /tmp/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}"]

  pgbouncer:
    container_name: pgbouncer
    image: edoburu/pgbouncer:latest
    restart: unless-stopped
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - AUTH_TYPE=scram-sha-256
      - POOL_MODE=transaction
      - ADMIN_USERS=${DB_USER},dbuser
    ports:
      - "5432:5432"
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost"]

volumes:
  pg_data:
