import { StyleSpecification } from "react-map-gl/maplibre";

export const PUBLIC_URL = new URL(import.meta.url).origin;

const ROAD_COLOUR_FAR = "rgb(160,160,160)";
const ROAD_COLOUR_CLOSE = "rgb(40,40,40)";
const WATER_OUTLINE = "rgb(100, 100, 100)";
const WATER_COLOUR = "rgb(11, 19, 23)";

const SHOW_MOTORWAYS = 4.8;
const SHOW_CASING = 6;

export const positronWxMap: StyleSpecification = {
  version: 8,
  name: "Positron-Wxmap",
  sources: {
    openmapraster: {
      type: "raster",
      maxzoom: 6,
      tileSize: 256,
      tiles: ["https://tiles.openfreemap.org/natural_earth/ne2sr/{z}/{x}/{y}.png"],
    },
    openmaptiles: {
      type: "vector",
      url: "https://tiles.openfreemap.org/planet",
    },
  },
  sprite: [
    { id: "default", url: "https://openmaptiles.github.io/positron-gl-style/sprite" },
    { id: "icons", url: `${PUBLIC_URL}/sprites/icons` },
    { id: "windbarbs", url: `${PUBLIC_URL}/sprites/windbarbs` },
  ],
  glyphs: `${PUBLIC_URL}/fonts/{fontstack}/{range}.pbf`,
  layers: [
    {
      id: "terrain",
      type: "raster",
      source: "openmapraster",
      "source-layer": "ne2_shaded",
      maxzoom: 14,
      paint: {
        "raster-opacity": ["interpolate", ["exponential", 1.5], ["zoom"], 0, 1, 6, 0.2],
        "raster-saturation": -1,
        "raster-brightness-max": 0.3,
        "raster-contrast": 0.5,
      },
    },
    {
      id: "waterfill",
      type: "fill",
      source: "openmaptiles",
      "source-layer": "water",
      paint: { "fill-color": WATER_COLOUR },
    },
    {
      id: "wateroutline",
      type: "line",
      source: "openmaptiles",
      "source-layer": "water",
      paint: { "line-color": WATER_OUTLINE, "line-width": 1 },
    },
    {
      id: "tunnel_motorway_casing",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      minzoom: SHOW_CASING,
      filter: ["all", ["==", "$type", "LineString"], ["all", ["==", "brunnel", "tunnel"], ["==", "class", "motorway"]]],
      layout: {
        "line-cap": "butt",
        "line-join": "miter",
        visibility: "visible",
      },
      paint: {
        "line-color": ["interpolate", ["exponential", 1.4], ["zoom"], 5.8, "black", 9, "#aaa"],
        "line-width": ["interpolate", ["exponential", 1.4], ["zoom"], 5.8, 0, 6, 3, 20, 40],
      },
    },
    {
      id: "tunnel_motorway_inner",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      minzoom: 6,
      filter: ["all", ["==", "$type", "LineString"], ["all", ["==", "brunnel", "tunnel"], ["==", "class", "motorway"]]],
      layout: {
        "line-cap": "round",
        "line-join": "round",
        visibility: "visible",
      },
      paint: {
        "line-color": ["interpolate", ["linear"], ["zoom"], SHOW_MOTORWAYS, ROAD_COLOUR_FAR, 8, ROAD_COLOUR_CLOSE],
        "line-width": ["interpolate", ["exponential", 1.4], ["zoom"], 4, 2, 6, 1.3, 20, 30],
      },
    },
    {
      id: "aeroway-taxiway",
      type: "line",
      source: "openmaptiles",
      "source-layer": "aeroway",
      minzoom: 12,
      filter: ["all", ["in", "class", "taxiway"]],
      layout: {
        "line-cap": "round",
        "line-join": "round",
        visibility: "visible",
      },
      paint: {
        "line-color": "hsl(0, 0%, 88%)",
        "line-opacity": 1,
        "line-width": ["interpolate", ["exponential", 1.55], ["zoom"], 12, 1.8, 20, 20],
      },
    },
    {
      id: "aeroway-area",
      type: "fill",
      source: "openmaptiles",
      "source-layer": "aeroway",
      minzoom: 12,
      filter: ["all", ["==", "$type", "Polygon"], ["in", "class", "runway", "taxiway"]],
      layout: { visibility: "visible" },
      paint: {
        "fill-color": "rgba(255, 255, 255, 1)",
        "fill-opacity": ["interpolate", ["exponential", 1], ["zoom"], 13, 0, 14, 1],
      },
    },
    {
      id: "aeroway-runway",
      type: "line",
      source: "openmaptiles",
      "source-layer": "aeroway",
      minzoom: 8,
      filter: ["all", ["in", "class", "runway"], ["==", "$type", "LineString"]],
      layout: {
        "line-cap": "round",
        "line-join": "round",
        visibility: "visible",
      },
      paint: {
        "line-color": "rgba(255, 255, 255, 1)",
        "line-opacity": 1,
        "line-width": ["interpolate", ["exponential", 1.5], ["zoom"], 8, 4, 17, 50],
      },
    },
    {
      id: "highway_major_casing",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      minzoom: SHOW_CASING,
      // filter: ["all", ["==", "$type", "LineString"], ["in", "class", "primary", "secondary", "tertiary", "trunk"]],
      filter: ["all", ["==", "$type", "LineString"], ["in", "class", "trunk"]],
      layout: {
        "line-cap": "butt",
        "line-join": "miter",
        visibility: "visible",
      },
      paint: {
        "line-color": ["interpolate", ["exponential", 1.4], ["zoom"], 5.8, "black", 9, "#aaa"],
        "line-dasharray": [12, 0],
        "line-width": ["interpolate", ["exponential", 1.3], ["zoom"], 10, 3, 20, 23],
      },
    },
    {
      id: "non_major_roads",
      source: "openmaptiles",
      "source-layer": "transportation",
      type: "line",
      filter: ["all", ["==", "$type", "LineString"], ["in", "class", "primary", "secondary", "tertiary"]],
      minzoom: 9,
      layout: {
        "line-cap": "round",
        "line-join": "miter",
        visibility: "visible",
      },
      paint: {
        "line-color": "rgb(20,20,20)",
        "line-opacity": 1,
        "line-width": ["interpolate", ["exponential", 1.3], ["zoom"], 9, 2, 20, 8],
      },
    },
    {
      // this takes over after zoom level 11 from highway_major_subtle
      id: "highway_major_inner",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      minzoom: 11,
      // filter: ["all", ["==", "$type", "LineString"], ["in", "class", "primary", "secondary", "tertiary", "trunk"]],
      filter: ["all", ["==", "$type", "LineString"], ["in", "class", "trunk"]],
      layout: {
        "line-cap": "round",
        "line-join": "round",
        visibility: "visible",
      },
      paint: {
        "line-color": ["interpolate", ["linear"], ["zoom"], SHOW_MOTORWAYS, ROAD_COLOUR_FAR, 8, ROAD_COLOUR_CLOSE],
        "line-opacity": 1,
        "line-width": ["interpolate", ["exponential", 1.3], ["zoom"], 10, 2, 20, 20],
      },
    },
    {
      id: "highway_major_subtle",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      minzoom: SHOW_MOTORWAYS,
      maxzoom: 11,
      // filter: ["all", ["==", "$type", "LineString"], ["in", "class", "primary", "secondary", "tertiary", "trunk"]],
      filter: ["all", ["==", "$type", "LineString"], ["in", "class", "trunk"]],
      layout: {
        "line-cap": "round",
        "line-join": "round",
        visibility: "visible",
      },
      paint: {
        "line-color": ["interpolate", ["linear"], ["zoom"], SHOW_MOTORWAYS, ROAD_COLOUR_FAR, 8, ROAD_COLOUR_CLOSE],
        "line-opacity": ["interpolate", ["exponential", 1.4], ["zoom"], 4, 0.5, 7, 0.8, 11, 1],
        "line-width": 1,
      },
    },
    {
      // adds an outline to motorways
      id: "highway_motorway_casing",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      minzoom: SHOW_MOTORWAYS,
      filter: [
        "all",
        ["==", "$type", "LineString"],
        ["all", ["!in", "brunnel", "bridge", "tunnel"], ["==", "class", "motorway"]],
      ],
      layout: {
        "line-cap": "butt",
        "line-join": "miter",
        visibility: "visible",
      },
      paint: {
        "line-color": ["interpolate", ["exponential", 1.4], ["zoom"], 5.8, "black", 9, "#aaa"],
        "line-dasharray": [2, 0],
        "line-width": ["interpolate", ["exponential", 1.4], ["zoom"], 5.8, 0, 7, 3, 20, 40],
      },
    },
    {
      id: "highway_motorway_inner",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      minzoom: SHOW_MOTORWAYS,
      filter: [
        "all",
        ["==", "$type", "LineString"],
        ["all", ["!in", "brunnel", "bridge", "tunnel"], ["==", "class", "motorway"]],
      ],
      layout: {
        "line-cap": "round",
        "line-join": "round",
        visibility: "visible",
      },
      paint: {
        "line-color": ["interpolate", ["linear"], ["zoom"], SHOW_MOTORWAYS, ROAD_COLOUR_FAR, 8, ROAD_COLOUR_CLOSE],
        "line-opacity": ["interpolate", ["exponential", 1], ["zoom"], 4, 0.1, 7, 0.8, 11, 1],
        "line-width": ["interpolate", ["exponential", 1.4], ["zoom"], 4, 1, 7, 1.3, 20, 30],
      },
    },
    {
      id: "highway_motorway_subtle",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      minzoom: SHOW_MOTORWAYS,
      maxzoom: 6,
      filter: ["all", ["==", "$type", "LineString"], ["==", "class", "motorway"]],
      layout: {
        "line-cap": "round",
        "line-join": "round",
        visibility: "visible",
      },
      paint: {
        "line-color": ["interpolate", ["linear"], ["zoom"], SHOW_MOTORWAYS, ROAD_COLOUR_FAR, 8, ROAD_COLOUR_CLOSE],
        "line-opacity": ["interpolate", ["exponential", 1], ["zoom"], 4, 0.5, 7, 0.8, 11, 1],
        "line-width": ["interpolate", ["exponential", 1.4], ["zoom"], 4, 1, 6, 1.3],
      },
    },
    {
      id: "highway_motorway_bridge_casing",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      minzoom: SHOW_MOTORWAYS,
      filter: ["all", ["==", "$type", "LineString"], ["all", ["==", "brunnel", "bridge"], ["==", "class", "motorway"]]],
      layout: {
        "line-cap": "butt",
        "line-join": "miter",
        visibility: "visible",
      },
      paint: {
        "line-color": ["interpolate", ["exponential", 1.4], ["zoom"], 5.8, "black", 9, "#aaa"],
        "line-dasharray": [2, 0],
        "line-opacity": ["interpolate", ["exponential", 1], ["zoom"], 4, 0.5, 7, 0.8, 11, 1],
        "line-width": ["interpolate", ["exponential", 1.4], ["zoom"], 5.8, 0, 6, 5, 20, 45],
      },
    },
    {
      id: "highway_motorway_bridge_inner",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      minzoom: SHOW_MOTORWAYS,
      filter: ["all", ["==", "$type", "LineString"], ["all", ["==", "brunnel", "bridge"], ["==", "class", "motorway"]]],
      layout: {
        "line-cap": "round",
        "line-join": "round",
        visibility: "visible",
      },
      paint: {
        "line-color": ["interpolate", ["linear"], ["zoom"], SHOW_MOTORWAYS, ROAD_COLOUR_FAR, 8, ROAD_COLOUR_CLOSE],
        "line-width": ["interpolate", ["exponential", 1.4], ["zoom"], 4, 2, 6, 1.3, 20, 30],
      },
    },
    {
      id: "highway_name_other",
      type: "symbol",
      source: "openmaptiles",
      "source-layer": "transportation_name",
      filter: ["all", ["!=", "class", "motorway"], ["==", "$type", "LineString"]],
      layout: {
        "symbol-placement": "line",
        "symbol-spacing": 660,
        "text-field": "{name:latin} {name:nonlatin}",
        "text-font": ["Metropolis-Regular"],
        "text-max-angle": 30,
        "text-pitch-alignment": "viewport",
        "text-rotation-alignment": "map",
        "text-size": 10,
        "text-transform": "uppercase",
        visibility: "visible",
      },
      paint: {
        "text-color": "#000",
        "text-halo-blur": 1,
        "text-halo-color": "#fff",
        "text-halo-width": 2,
        "text-translate": [0, 0],
      },
    },
    {
      id: "highway_name_motorway",
      type: "symbol",
      source: "openmaptiles",
      "source-layer": "transportation_name",
      filter: ["all", ["==", "$type", "LineString"], ["==", "class", "motorway"]],
      layout: {
        "symbol-placement": "line",
        "symbol-spacing": 350,
        "text-field": "{ref}",
        "text-font": ["Metropolis-Regular"],
        "text-pitch-alignment": "viewport",
        "text-rotation-alignment": "viewport",
        "text-size": 10,
        visibility: "visible",
      },
      paint: {
        "text-color": "#000",
        "text-halo-blur": 1,
        "text-halo-color": "#fff",
        "text-halo-width": 2,
        "text-translate": [0, 2],
      },
    },
    {
      id: "boundary_state",
      type: "line",
      source: "openmaptiles",
      "source-layer": "boundary",
      filter: ["all", ["==", "admin_level", 4], ["==", "maritime", 0]],
      layout: {
        "line-cap": "round",
        "line-join": "round",
        visibility: "visible",
      },
      paint: {
        "line-blur": 0.4,
        "line-color": "rgb(0, 0, 0)",
        // "line-dasharray": [2, 2],
        "line-opacity": 1,
        "line-width": 1,
      },
    },
    {
      id: "boundary_country_z0-4",
      type: "line",
      source: "openmaptiles",
      "source-layer": "boundary",
      maxzoom: 24,
      filter: ["all", ["==", "admin_level", 2], ["==", "maritime", 0]],
      layout: {
        "line-cap": "round",
        "line-join": "round",
        visibility: "visible",
      },
      paint: {
        "line-blur": 0.4,
        "line-color": "rgba(0, 0, 0, 1)",
        "line-opacity": 1,
        "line-width": ["interpolate", ["linear"], ["zoom"], 3, 1, 22, 20],
      },
    },
    {
      id: "boundary_country_z5-",
      type: "line",
      source: "openmaptiles",
      "source-layer": "boundary",
      minzoom: 5,
      filter: ["all", ["==", "admin_level", 2], ["!has", "claimed_by"], ["==", "maritime", 0]],
      layout: {
        "line-cap": "round",
        "line-join": "round",
        visibility: "visible",
      },
      paint: {
        "line-blur": ["interpolate", ["linear"], ["zoom"], 0, 0.4, 22, 4],
        "line-color": "rgba(0, 0, 0, 1)",
        "line-opacity": 1,
        "line-width": ["interpolate", ["exponential", 1.1], ["zoom"], 3, 1, 22, 20],
      },
    },
    {
      id: "water_name",
      type: "symbol",
      source: "openmaptiles",
      "source-layer": "water_name",
      filter: ["==", "$type", "LineString"],
      layout: {
        "symbol-placement": "line",
        "symbol-spacing": 500,
        "text-field": "{name:latin}\n{name:nonlatin}",
        "text-font": ["Metropolis-Regular-Italic"],
        "text-rotation-alignment": "map",
        "text-size": 12,
        visibility: "visible",
      },
      paint: {
        "text-color": "rgb(157,169,177)",
        "text-halo-blur": 1,
        "text-halo-color": "rgb(242,243,240)",
        "text-halo-width": 1,
      },
    },
    {
      id: "place_town",
      type: "symbol",
      source: "openmaptiles",
      "source-layer": "place",
      maxzoom: 15,
      filter: ["all", ["==", "$type", "Point"], ["==", "class", "town"]],
      layout: {
        "icon-image": ["step", ["zoom"], "circle-11", 8, ""],
        "icon-size": 0.4,
        "text-anchor": ["step", ["zoom"], "left", 8, "center"],
        "text-field": "{name:latin}\n{name:nonlatin}",
        "text-font": ["Metropolis-Regular"],
        "text-justify": "left",
        "text-offset": [0.5, 0.2],
        "text-size": 10,
        "text-transform": "uppercase",
        visibility: "visible",
      },
      paint: {
        "icon-opacity": 0.7,
        "text-color": "rgba(0, 0, 0, 1)",
        "text-halo-blur": 1,
        "text-halo-color": "rgb(242,243,240)",
        "text-halo-width": 1,
      },
    },
    {
      id: "place_city",
      type: "symbol",
      source: "openmaptiles",
      "source-layer": "place",
      maxzoom: 14,
      filter: [
        "all",
        ["==", "$type", "Point"],
        ["all", ["!=", "capital", 2], ["==", "class", "city"], [">", "rank", 3]],
      ],
      layout: {
        "icon-image": ["step", ["zoom"], "circle-11", 8, ""],
        "icon-size": 0.4,
        "text-anchor": ["step", ["zoom"], "left", 8, "center"],
        "text-field": "{name:latin}\n{name:nonlatin}",
        "text-font": ["Metropolis-Regular"],
        "text-justify": "left",
        "text-offset": [0.5, 0.2],
        "text-size": 10,
        "text-transform": "uppercase",
        visibility: "visible",
      },
      paint: {
        "icon-opacity": 0.7,
        "text-color": "rgba(0, 0, 0, 1)",
        "text-halo-blur": 1,
        "text-halo-color": "rgb(242,243,240)",
        "text-halo-width": 1,
      },
    },
    {
      id: "place_capital",
      type: "symbol",
      source: "openmaptiles",
      "source-layer": "place",
      maxzoom: 12,
      filter: ["all", ["==", "$type", "Point"], ["all", ["==", "capital", 2], ["==", "class", "city"]]],
      layout: {
        "icon-image": ["step", ["zoom"], "star-11", 8, ""],
        "icon-size": 1,
        "text-anchor": ["step", ["zoom"], "left", 8, "center"],
        "text-field": "{name:latin}\n{name:nonlatin}",
        "text-font": ["Metropolis-Regular"],
        "text-justify": "left",
        "text-offset": [0.5, 0.2],
        "text-size": 14,
        "text-transform": "uppercase",
        visibility: "visible",
      },
      paint: {
        "icon-opacity": 0.7,
        "text-color": "rgba(0, 0, 0, 1)",
        "text-halo-blur": 1,
        "text-halo-color": "rgb(242,243,240)",
        "text-halo-width": 1,
      },
    },
    {
      id: "place_city_large",
      type: "symbol",
      source: "openmaptiles",
      "source-layer": "place",
      maxzoom: 12,
      filter: [
        "all",
        ["==", "$type", "Point"],
        ["all", ["!=", "capital", 2], ["<=", "rank", 3], ["==", "class", "city"]],
      ],
      layout: {
        "icon-image": ["step", ["zoom"], "circle-11", 8, ""],
        "icon-size": 0.4,
        "text-anchor": ["step", ["zoom"], "left", 8, "center"],
        "text-field": "{name:latin}\n{name:nonlatin}",
        "text-font": ["Metropolis-Regular"],
        "text-justify": "left",
        "text-offset": [0.5, 0.2],
        "text-size": 14,
        "text-transform": "uppercase",
        visibility: "visible",
      },
      paint: {
        "icon-opacity": 0.7,
        "text-color": "rgba(0, 0, 0, 1)",
        "text-halo-blur": 1,
        "text-halo-color": "rgb(242,243,240)",
        "text-halo-width": 1,
      },
    },
    {
      id: "place_state",
      type: "symbol",
      source: "openmaptiles",
      "source-layer": "place",
      maxzoom: 12,
      filter: ["all", ["==", "$type", "Point"], ["==", "class", "state"]],
      layout: {
        "text-field": "{name:latin}\n{name:nonlatin}",
        "text-font": ["Metropolis-Regular-Italic"],
        "text-size": 14,
        "text-transform": "uppercase",
        visibility: "visible",
        "text-max-width": 8,
      },
      paint: {
        "text-color": "rgb(113, 129, 144)",
        "text-halo-blur": 1,
        "text-halo-color": "rgb(242,243,240)",
        "text-halo-width": 1,
      },
    },
  ],
};
