import { StyleSpecification } from "react-map-gl/maplibre";

const pathDetails = new URL(import.meta.url);
export const PUBLIC_URL = `${pathDetails.protocol}//${pathDetails.hostname}${
  pathDetails.port ? `:${pathDetails.port}` : ""
}${
  process.env.NODE_ENV === "production"
    ? ""
    : pathDetails.pathname.replace("src/assets/map-styles/positron-wxmap.ts", "")
}`;

export const positronWxMap: StyleSpecification = {
  version: 8,
  name: "Positron-Wxmap",
  metadata: {
    "mapbox:autocomposite": false,
    "mapbox:groups": {
      "101da9f13b64a08fa4b6ac1168e89e5f": {
        collapsed: false,
        name: "Places",
      },
      a14c9607bc7954ba1df7205bf660433f: { name: "Boundaries" },
      b6371a3f2f5a9932464fa3867530a2e5: {
        collapsed: false,
        name: "Transportation",
      },
    },
    "mapbox:type": "template",
    "openmaptiles:mapbox:owner": "openmaptiles",
    "openmaptiles:mapbox:source:url": "mapbox://openmaptiles.4qljc88t",
    "openmaptiles:version": "3.x",
    "maputnik:renderer": "mlgljs",
  },
  sources: {
    openmaptiles: {
      type: "vector",
      url: "https://tiles.openfreemap.org/planet",
    },
  },
  sprite: [
    { id: "default", url: "https://openmaptiles.github.io/positron-gl-style/sprite" },
    // { id: "windbarbs", url: `${PUBLIC_URL}/sprites/windbarbs` },
  ],
  glyphs: "https://api.maptiler.com/fonts/{fontstack}/{range}.pbf?key=xDuB4axhGsuzLiFvvDiF",
  layers: [
    {
      id: "wateroutline",
      type: "line",
      source: "openmaptiles",
      "source-layer": "water",
      paint: { "line-color": "rgb(44, 44, 44)", "line-width": 1.5 },
    },
    {
      id: "boundary_state",
      type: "line",
      metadata: { "mapbox:group": "a14c9607bc7954ba1df7205bf660433f" },
      source: "openmaptiles",
      "source-layer": "boundary",
      filter: ["all", ["==", "admin_level", 4], ["==", "maritime", 0]],
      layout: {
        "line-cap": "round",
        "line-join": "round",
        visibility: "visible",
      },
      paint: {
        "line-blur": 0.4,
        "line-color": "rgba(0, 0, 0, 1)",
        "line-dasharray": [2, 2],
        "line-opacity": 1,
        "line-width": 1.5,
      },
    },
    {
      id: "boundary_country_z0-4",
      type: "line",
      metadata: { "mapbox:group": "a14c9607bc7954ba1df7205bf660433f" },
      source: "openmaptiles",
      "source-layer": "boundary",
      maxzoom: 24,
      filter: ["all", ["==", "admin_level", 2], ["==", "maritime", 0]],
      layout: {
        "line-cap": "round",
        "line-join": "round",
        visibility: "visible",
      },
      paint: {
        "line-blur": 0.4,
        "line-color": "rgba(0, 0, 0, 1)",
        "line-opacity": 1,
        "line-width": ["interpolate", ["linear"], ["zoom"], 3, 1, 22, 20],
      },
    },
    {
      id: "boundary_country_z5-",
      type: "line",
      metadata: { "mapbox:group": "a14c9607bc7954ba1df7205bf660433f" },
      source: "openmaptiles",
      "source-layer": "boundary",
      minzoom: 5,
      filter: ["all", ["==", "admin_level", 2], ["!has", "claimed_by"], ["==", "maritime", 0]],
      layout: {
        "line-cap": "round",
        "line-join": "round",
        visibility: "visible",
      },
      paint: {
        "line-blur": ["interpolate", ["linear"], ["zoom"], 0, 0.4, 22, 4],
        "line-color": "rgba(0, 0, 0, 1)",
        "line-opacity": 1,
        "line-width": ["interpolate", ["exponential", 1.1], ["zoom"], 3, 1, 22, 20],
      },
    },
    {
      id: "water_name",
      type: "symbol",
      source: "openmaptiles",
      "source-layer": "water_name",
      filter: ["==", "$type", "LineString"],
      layout: {
        "symbol-placement": "line",
        "symbol-spacing": 500,
        "text-field": "{name:latin}\n{name:nonlatin}",
        "text-font": ["Metropolis Medium Italic", "Noto Sans Italic"],
        "text-rotation-alignment": "map",
        "text-size": 12,
        visibility: "visible",
      },
      paint: {
        "text-color": "rgb(157,169,177)",
        "text-halo-blur": 1,
        "text-halo-color": "rgb(242,243,240)",
        "text-halo-width": 1,
      },
    },
    {
      id: "place_town",
      type: "symbol",
      metadata: { "mapbox:group": "101da9f13b64a08fa4b6ac1168e89e5f" },
      source: "openmaptiles",
      "source-layer": "place",
      maxzoom: 15,
      filter: ["all", ["==", "$type", "Point"], ["==", "class", "town"]],
      layout: {
        "icon-image": ["step", ["zoom"], "circle-11", 8, ""],
        "icon-size": 0.4,
        "text-anchor": ["step", ["zoom"], "left", 8, "center"],
        "text-field": "{name:latin}\n{name:nonlatin}",
        "text-font": ["Metropolis Regular", "Noto Sans Regular"],
        "text-justify": "left",
        "text-offset": [0.5, 0.2],
        "text-size": 10,
        "text-transform": "uppercase",
        visibility: "visible",
      },
      paint: {
        "icon-opacity": 0.7,
        "text-color": "rgba(0, 0, 0, 1)",
        "text-halo-blur": 1,
        "text-halo-color": "rgb(242,243,240)",
        "text-halo-width": 1,
      },
    },
    {
      id: "place_city",
      type: "symbol",
      metadata: { "mapbox:group": "101da9f13b64a08fa4b6ac1168e89e5f" },
      source: "openmaptiles",
      "source-layer": "place",
      maxzoom: 14,
      filter: [
        "all",
        ["==", "$type", "Point"],
        ["all", ["!=", "capital", 2], ["==", "class", "city"], [">", "rank", 3]],
      ],
      layout: {
        "icon-image": ["step", ["zoom"], "circle-11", 8, ""],
        "icon-size": 0.4,
        "text-anchor": ["step", ["zoom"], "left", 8, "center"],
        "text-field": "{name:latin}\n{name:nonlatin}",
        "text-font": ["Metropolis Regular", "Noto Sans Regular"],
        "text-justify": "left",
        "text-offset": [0.5, 0.2],
        "text-size": 10,
        "text-transform": "uppercase",
        visibility: "visible",
      },
      paint: {
        "icon-opacity": 0.7,
        "text-color": "rgba(0, 0, 0, 1)",
        "text-halo-blur": 1,
        "text-halo-color": "rgb(242,243,240)",
        "text-halo-width": 1,
      },
    },
    {
      id: "place_capital",
      type: "symbol",
      metadata: { "mapbox:group": "101da9f13b64a08fa4b6ac1168e89e5f" },
      source: "openmaptiles",
      "source-layer": "place",
      maxzoom: 12,
      filter: ["all", ["==", "$type", "Point"], ["all", ["==", "capital", 2], ["==", "class", "city"]]],
      layout: {
        "icon-image": ["step", ["zoom"], "star-11", 8, ""],
        "icon-size": 1,
        "text-anchor": ["step", ["zoom"], "left", 8, "center"],
        "text-field": "{name:latin}\n{name:nonlatin}",
        "text-font": ["Metropolis Regular", "Noto Sans Regular"],
        "text-justify": "left",
        "text-offset": [0.5, 0.2],
        "text-size": 14,
        "text-transform": "uppercase",
        visibility: "visible",
      },
      paint: {
        "icon-opacity": 0.7,
        "text-color": "rgba(0, 0, 0, 1)",
        "text-halo-blur": 1,
        "text-halo-color": "rgb(242,243,240)",
        "text-halo-width": 1,
      },
    },
    {
      id: "place_city_large",
      type: "symbol",
      metadata: { "mapbox:group": "101da9f13b64a08fa4b6ac1168e89e5f" },
      source: "openmaptiles",
      "source-layer": "place",
      maxzoom: 12,
      filter: [
        "all",
        ["==", "$type", "Point"],
        ["all", ["!=", "capital", 2], ["<=", "rank", 3], ["==", "class", "city"]],
      ],
      layout: {
        "icon-image": ["step", ["zoom"], "circle-11", 8, ""],
        "icon-size": 0.4,
        "text-anchor": ["step", ["zoom"], "left", 8, "center"],
        "text-field": "{name:latin}\n{name:nonlatin}",
        "text-font": ["Metropolis Regular", "Noto Sans Regular"],
        "text-justify": "left",
        "text-offset": [0.5, 0.2],
        "text-size": 14,
        "text-transform": "uppercase",
        visibility: "visible",
      },
      paint: {
        "icon-opacity": 0.7,
        "text-color": "rgba(0, 0, 0, 1)",
        "text-halo-blur": 1,
        "text-halo-color": "rgb(242,243,240)",
        "text-halo-width": 1,
      },
    },
    {
      id: "place_state",
      type: "symbol",
      metadata: { "mapbox:group": "101da9f13b64a08fa4b6ac1168e89e5f" },
      source: "openmaptiles",
      "source-layer": "place",
      maxzoom: 12,
      filter: ["all", ["==", "$type", "Point"], ["==", "class", "state"]],
      layout: {
        "text-field": "{name:latin}\n{name:nonlatin}",
        "text-font": ["Metropolis Regular Italic", "Noto Sans Regular"],
        "text-size": 14,
        "text-transform": "uppercase",
        visibility: "visible",
        "text-max-width": 8,
      },
      paint: {
        "text-color": "rgb(113, 129, 144)",
        "text-halo-blur": 1,
        "text-halo-color": "rgb(242,243,240)",
        "text-halo-width": 1,
      },
    },
  ],
};
