export const OFFICE_REGION_MAP = {
  PSPC: {
    "1_PSPC": "BC & Yukon",
    "2_BC": "British Columbia",
    "2_YT": "Yukon",
    BC: "British Columbia",
    BC_YT: "BC & The Yukon",
    Assessment: "Assessment",
    Avalanche: "Avalanche",
    Flexible: "Flexible",
    Flexible_Ops: "Flexible_Ops",
  },
  PASPC: {
    PASPC: "Prairies & Arctic",
    AB: "Alberta",
    Arctic: "Arctic",
    Baffin: "Baffin Island",
    Flexible: "Flexible",
    ISR: "Inuvialuit Settlement Region",
    Kitikmeot: "Kitikmeot",
    Kivalliq: "Kivalliq",
    MB: "Manitoba",
    "MB-Arctic": "Manitoba & Eastern Arctic",
    MK: "Mackenzie",
    NT: "Northwest Territories",
    NU: "Nunavut",
    Prairies: "Prairies",
    SK: "Saskatchewan",
  },
  OSPC: {
    "1_OSPC": "Ontario",
    "2_ON_N": "Northern Ontario",
    "2_ON_S": "Southern Ontario",
    OSPC: "Ontario",
    ON: "Ontario",
    ON_N: "Northern Ontario",
    ON_S: "Southern Ontario",
    Flexible: "Flexible",
  },
  QSPC: {
    "1_QSPC": "Quebec",
    "2_QC_N": "Northern Quebec",
    "2_QC_S": "Southern Quebec",
    QSPC: "Quebec",
    QC: "Quebec",
    QC_N: "Northern Quebec",
    QC_S: "Southern Quebec",
    Flexible: "Flexible",
  },
  ASPC: {
    "1_ASPC": "Atlantic",
    "2_NB": "New Brunswick",
    "2_NB-NS-PEI": "Maritimes",
    "2_NL": "Newfoundland",
    "2_NS": "Nova Scotia",
    "2_PEI": "Prince Edward Island",
    ASPC: "Atlantic & Maritimes",
    Atlantic: "Atlantic",
    Flexible: "Flexible",
    Maritimes: "Maritimes",
    NL: "Newfoundland",
  },
  NLWO: { NL: "Newfoundland" },
} as const;

export const OUTLOOK_ROOT_DIR = "~/data/" as const;
