export const NAVCAN_IMAGE_URL = "https://plan.navcanada.ca/weather/images/";

export const OUTLOOK_OFFICES = ["pspc", "paspc", "ospc", "qspc", "aspc", "nlwo"] as const;

export const OFFICE_REGION_MAP = {
  "1_pspc": "BC & Yukon",
  "2_bc": "British Columbia",
  "2_yt": "Yukon",
  bc: "British Columbia",
  bc_yt: "BC & Yukon",
  "bc-yt": "BC & Yukon",
  yt: "Yukon",
  assessment: "Assessment",
  avalanche: "Avalanche",
  flexible: "Flexible",
  flexible_ops: "Flexible Ops",
  paspc: "Prairies & Arctic",
  ab: "Alberta",
  arctic: "Arctic",
  baffin: "Baffin Island",
  isr: "Inuvialuit Settlement Region",
  kitikmeot: "Kitikmeot",
  kivalliq: "Kivalliq",
  mb: "Manitoba",
  "mb-arctic": "Manitoba & Eastern Arctic",
  mk: "Mackenzie",
  nt: "Northwest Territories",
  nu: "Nunavut",
  prairies: "Prairies",
  sk: "Saskatchewan",
  "1_ospc": "Ontario",
  "2_on_n": "Northern Ontario",
  "2_on_s": "Southern Ontario",
  ospc: "Ontario",
  on: "Ontario",
  on_n: "Northern Ontario",
  on_s: "Southern Ontario",
  "1_qspc": "Quebec",
  "2_qc_n": "Northern Quebec",
  "2_qc_s": "Southern Quebec",
  qspc: "Quebec",
  qc: "Quebec",
  qc_n: "Northern Quebec",
  qc_s: "Southern Quebec",
  "1_aspc": "Atlantic",
  "2_nb": "New Brunswick",
  "2_nb-ns-pei": "Maritimes",
  "2_nl": "Newfoundland",
  "2_ns": "Nova Scotia",
  "2_pei": "Prince Edward Island",
  aspc: "Atlantic & Maritimes",
  atlantic: "Atlantic",
  maritimes: "Maritimes",
  nl: "Newfoundland",
} as const;
